version: '3.0'
services:
  db:
    image: postgres
    restart: always
    hostname: dbmarketplace
    ports:
      - "5432:5432"
    networks:
      - metricas
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=marketplace
networks:
  metricas:
    driver: bridge